steps:
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**
            - tests/**

  - label: ":test_tube: Tests"
    plugins:
      - docker-compose#v5.12.1:
          run: tests
          config: compose.yaml

  - label: ":book: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: bedrock-summarize
